apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service # responsible for enabling network access to the mongodb pod
spec:
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongo_service.port }}
      targetPort: {{ .Values.mongo_service.targetPort }}
