apiVersion: v1 
kind: Service 
metadata: 
  name: flask-service-np
  namespace: development
spec: 
  selector: 
    app: todo 
  type: NodePort 
  ports: 
    - name: http 
      port: 5000 
      targetPort: 5000