apiVersion: v1
kind: Service
metadata:
  name: flask-service-lb
  namespace: development
spec:
  type: LoadBalancer # provides a public ip to which external users can connect
  ports:
    - port: 5000
      #protocol: TCP
      targetPort: 5000
  selector:
    app: todo
