apiVersion: v1
kind: Service
metadata:
  name: mongodb-service # responsible for enabling network access to the mongodb pod
  namespace: development
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
